# Generated by Django 3.1.1 on 2020-10-22 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'db_table': 'carrito',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.carrito')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_realizacion', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('id_carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carro.carrito')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cliente')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=10)),
                ('id_pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carro.pedido')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['fecha_pago'],
            },
        ),
    ]
