# Generated by Django 3.1.1 on 2020-11-18 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('cupon', models.IntegerField()),
                ('costo_envio', models.IntegerField()),
                ('total_compra', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='datos_envio_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=70)),
                ('adress2', models.CharField(max_length=70, null=True)),
                ('country', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('zip_code', models.CharField(max_length=70)),
                ('metodo_envio', models.CharField(max_length=70)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Datos_envio_cliente',
            },
        ),
    ]
