# Generated by Django 3.1.1 on 2020-11-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'db_table': 'carrito',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.IntegerField()),
                ('metodo_pago', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('total', models.IntegerField()),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.pago')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['fecha_realizacion'],
            },
        ),
    ]
