# Generated by Django 3.1.3 on 2020-11-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carro.pago'),
        ),
    ]
