# Generated by Django 3.1.3 on 2020-11-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_pedido_pago_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pago_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.pago'),
        ),
    ]
